=== s215741/MateuszDurka/faktura.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="faktura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="numer" type="xs:string"/>
                <xs:element name="data" type="xs:date"/>
                <xs:element name="sprzedawca" type="podmiot"/>
                <xs:element name="nabywca" type="podmiot"/>
                <xs:element name="pozycje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pozycja" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nazwa" type="xs:string"/>
                                        <xs:element name="ilosc" type="xs:integer"/>
                                        <xs:element name="cena" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="podmiot">
        <xs:sequence>
            <xs:element name="nazwa" type="xs:string"/>
            <xs:element name="nip" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== s215741/MateuszDurka/faktura.xml
<?xml version="1.0" encoding="UTF-8"?>
<faktura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="faktura.xsd">

    <numer>FV/2025/001</numer>
    <data>2025-11-15</data>

    <sprzedawca>
        <nazwa>Firma Testowa</nazwa>
        <nip>1234567890</nip>
    </sprzedawca>

    <nabywca>
        <nazwa>Klient XYZ</nazwa>
        <nip>9876543210</nip>
    </nabywca>

    <pozycje>
        <pozycja>
            <nazwa>Produkt A</nazwa>
            <ilosc>2</ilosc>
            <cena>50</cena>
        </pozycja>

        <pozycja>
            <nazwa>Produkt B</nazwa>
            <ilosc>1</ilosc>
            <cena>120</cena>
        </pozycja>
    </pozycje>

</faktura>
